spring:
  application:
    name: booking-tours-dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# SpringDoc OpenAPI (Swagger) Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: false
